

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rxd]
set_property IOSTANDARD LVCMOS33 [get_ports txd]

set_property PACKAGE_PIN K17 [get_ports clk]
set_property PACKAGE_PIN P14 [get_ports rst_n]
set_property PACKAGE_PIN M18 [get_ports rxd]
set_property PACKAGE_PIN M17 [get_ports txd]

set_property PACKAGE_PIN M18 [get_ports rx_master]
set_property PACKAGE_PIN M17 [get_ports tx_master]
set_property IOSTANDARD LVCMOS33 [get_ports tx_master]
set_property IOSTANDARD LVCMOS33 [get_ports tx3_slave]
set_property IOSTANDARD LVCMOS33 [get_ports tx2_slave]
set_property IOSTANDARD LVCMOS33 [get_ports tx1_slave]
set_property IOSTANDARD LVCMOS33 [get_ports tx0_slave]
set_property IOSTANDARD LVCMOS33 [get_ports rx_master]
set_property IOSTANDARD LVCMOS33 [get_ports rx3_slave]
set_property IOSTANDARD LVCMOS33 [get_ports rx2_slave]
set_property IOSTANDARD LVCMOS33 [get_ports rx1_slave]
set_property IOSTANDARD LVCMOS33 [get_ports rx0_slave]
set_property PACKAGE_PIN G20 [get_ports rx0_slave]
set_property PACKAGE_PIN G18 [get_ports rx1_slave]
set_property PACKAGE_PIN J20 [get_ports rx2_slave]
set_property PACKAGE_PIN L20 [get_ports rx3_slave]
set_property PACKAGE_PIN F19 [get_ports tx0_slave]
set_property PACKAGE_PIN G19 [get_ports tx1_slave]
set_property PACKAGE_PIN H17 [get_ports tx2_slave]
set_property PACKAGE_PIN K19 [get_ports tx3_slave]
